FROM golang:alpine AS builder

WORKDIR /home

RUN go mod init hello

COPY hello.go .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hello .

# Execution stage
FROM scratch

WORKDIR /home

COPY --from=builder /home/hello .

ENTRYPOINT ["/home/hello"]

